server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always


spring:
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/project/**
          filters:
            - AuthenticationFilter

        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/task/**
          filters:
            - AuthenticationFilter

        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/team/**
          filters:
            - AuthenticationFilter



  application:
    name: GATEWAY-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
